name: gru_songs
description: "A feature packed local music player."
publish_to: "none"
version: 3.14.6-beta+200

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.16
  audio_session: ^0.2.2
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  flutter_riverpod: ^3.1.0
  equatable: ^2.0.8
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.1
  intl: ^0.20.2
  uuid: ^4.3.3
  file_picker: ^10.3.8
  crypto: ^3.0.7
  path: ^1.9.1
  sqflite: ^2.3.0
  audio_metadata_reader: ^1.4.2
  metadata_god: ^1.1.0
  permission_handler: ^11.1.0
  archive: ^3.6.1
  share_plus: ^10.1.4
  package_info_plus: ^8.0.2
  image: ^4.3.0
  audio_waveforms: ^1.3.0
  ffmpeg_kit_flutter_new_min: ^3.1.0
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  mockito: ^5.4.5
  build_runner: ^2.4.9
  shared_preferences_platform_interface: ^2.3.2
  matcher: ^0.12.17
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
