name: gru_songs
description: A high-performance music streaming app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.16
  audio_session: ^0.2.2
  http: ^1.2.1
  cached_network_image: ^3.3.1
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true